name: weather
description: weather app.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.2.0
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_animator: ^3.1.1
  flutter_bloc: ^7.0.1
  flutter_svg: ^0.22.0
  get_it: ^7.1.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  injectable: ^1.4.1
  intl: ^0.17.0
  json_annotation: ^4.0.1
  retrofit: ^2.0.0  
  simple_animations: ^3.1.1

dev_dependencies:
  auto_route_generator: ^2.1.0  
  build_runner: ^2.0.5
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.3
  lint: ^1.5.3  
  retrofit_generator: ^2.0.0+2  

flutter:
  uses-material-design: true

  assets:
    - assets/images/